### ISSUE TITLE
Doesen't work

### ISSUE THREAD

**Issue by slash-se** [volkanunal/Esp8266BasedCoronaVirusTracking#1]
When I try to upload your code on my ESP8266 it doesen't work with latest library.
So for my case I make a few changes in corona.ino file
at row 29 
``` lcd.begin(16, 2); ```

and after that initialize LSD with
``` lcd.init();```

**Comment by embedded4ever** [comment]
Hi, @slash-se, is it working now?
Here is the library that i used -> https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library.

**Comment by slash-se** [comment]
Hello @volkanunal. after my changes for me - working, I am use library with same name but now I see its different
https://github.com/marcoschwartz/LiquidCrystal_I2C.git

**Comment by embedded4ever** [comment]
Okey, i hope that you and your family are safe.
